version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:80"
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
